#!/bin/bash

# Firewallset: A script to enable and disable the firewall, called by BOINCOS helper.
# Author:
#		- Delta

case $1 in
	"on"		)		sudo ufw enable && sudo ufw default deny && sudo ufw allow SSH && sudo ufw allow 31416;;
	"off"		)		sudo ufw disable;;
	"reset"		)		sudo ufw reset;;
esac
